### PR TITLE
feat(docs): add README-CN file

### PR DESCRIPTION
**Pull request by BokaQin**
Closes # 

## ✅ Checks

- [ ✅] My pull request adheres to the code style of this project
- [ ✅] My code requires changes to the documentation
- [✅ ] I have updated the documentation as required
- [✅ ] All the tests have passed
- [✅ ] Branch name follows `type/descript` (e.g. `feature/add-llm-agents`)
- [ ✅] Ready for code review

## ℹ Additional Information

HI there! I add the README-CN.md for research-town, it's great work.

### CODE REVIEW

**Comment by lwaekfjlk** [comment]
Thanks for your contribution! @BokaQin Maybe we can add a link in the main readme section to allow user to switch between english and Chinese?

**Comment by BokaQin** [comment]
That's great idea! give me a sec.

**Comment by BokaQin** [comment]
I am already add the LInk! if my work can add in that will be great.

**Review by lwaekfjlk — APPROVED** [review]
LGTM

**Pull request merged**
